plugins = []
headers = []
redirects = []

[functions]

  [functions."*"]

[build]
publish = ".netlify-static"
publishOrigin = "config"
commandOrigin = "config"
command = "bash scripts/prepare-netlify.sh"

  [build.environment]
  NODE_VERSION = "20"

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]