approval_policy = "never"
sandbox_mode = "workspace-write"
model = "gpt-5.4-mini"
model_reasoning_effort = "xhigh"

[mcp]
remote_mcp_client_enabled = true

[features]
multi_agent = true

[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS = "1"

[sandbox_workspace_write]
network_access = true

[mcp_servers.stitch]
url = "https://stitch.googleapis.com/mcp"

[mcp_servers.stitch.http_headers]
X-Goog-Api-Key = "AQ.Ab8RN6JhzLE8C_2hG5M2lzXX8SNsTlL4QgvJGVEvCmjG1oOMpg"

[mcp_servers.figma_desktop]
url = "http://127.0.0.1:3845/mcp"

[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp?project_ref=qtouztmyuemwxxtmaqjm&features=docs%2Caccount%2Cdatabase%2Cdebugging%2Cbranching%2Cfunctions%2Cdevelopment%2Cstorage"

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"

[mcp_servers.strip]
url = "https://mcp.stripe.com"

[projects."C:\\Users\\rimur"]
trust_level = "trusted"

[windows]
sandbox = "elevated"

[plugins."github@openai-curated"]
enabled = true

[plugins."stripe@openai-curated"]
enabled = true

[plugins."cloudflare@openai-curated"]
enabled = true

[plugins."build-web-apps@openai-curated"]
enabled = true

[plugins."test-android-apps@openai-curated"]
enabled = true

[plugins."build-ios-apps@openai-curated"]
enabled = true

[[skills.config]]
path = "/mnt/c/Users/rimur/.codex/skills/roblox-studio-connect/SKILL.md"
enabled = false

[[skills.config]]
path = "/mnt/c/Users/rimur/.codex/skills/unity-connect/SKILL.md"
enabled = false
